package com.idun.app.data

import android.content.Context
import org.json.JSONObject
import java.io.BufferedReader

/**
 * Maps a raw recipe-ingredient line to a canonical [Food] id.
 *
 * Patterns live in `foods_catalog.json` (bundled asset, generated by
 * `scripts/foods/build_catalog.py` — that script is the source of truth and
 * is gated on zero unmatched lines across the recipe corpus). At first use
 * we read the asset, compile the regexes once, and cache them on the
 * companion so subsequent activities pay nothing.
 *
 * Match semantics mirror the Python build step: case-insensitive search,
 * first matching pattern wins, catalog order is meaningful (specific
 * compounds like "garlic powder" come before the bare "garlic").
 */
class FoodResolver(private val context: Context) {

    fun resolve(ingredientNameEn: String): String? = match(compiled(), ingredientNameEn)

    private fun compiled(): List<CompiledEntry> {
        cached?.let { return it }
        synchronized(FoodResolver::class.java) {
            cached?.let { return it }
            val raw = context.assets.open("foods_catalog.json")
                .bufferedReader().use(BufferedReader::readText)
            val parsed = parseCatalog(raw)
            cached = parsed
            return parsed
        }
    }

    internal data class CompiledEntry(val foodId: String, val patterns: List<Regex>)

    companion object {
        internal fun parseCatalog(json: String): List<CompiledEntry> {
            val arr = JSONObject(json).getJSONArray("foods")
            val out = ArrayList<CompiledEntry>(arr.length())
            for (i in 0 until arr.length()) {
                val e = arr.getJSONObject(i)
                val patternsArr = e.optJSONArray("patterns") ?: continue
                if (patternsArr.length() == 0) continue
                val regexes = ArrayList<Regex>(patternsArr.length())
                for (j in 0 until patternsArr.length()) {
                    regexes.add(Regex(patternsArr.getString(j), RegexOption.IGNORE_CASE))
                }
                out.add(CompiledEntry(e.getString("id"), regexes))
            }
            return out
        }

        internal fun match(entries: List<CompiledEntry>, ingredientNameEn: String): String? {
            val needle = ingredientNameEn.lowercase().trim()
            if (needle.isEmpty()) return null
            for (entry in entries) {
                for (pat in entry.patterns) {
                    if (pat.containsMatchIn(needle)) return entry.foodId
                }
            }
            return null
        }

        @Volatile
        private var cached: List<CompiledEntry>? = null
    }
}
