package com.idun.app.data

/**
 * One canonical food in the ingredients-pedagogy corpus. Source-of-truth
 * is the Miam knowledge base markdown at
 * `Miam/miam-knowledge-base/docs/life/ingredients-pedagogy.md` — the
 * `foods.json` asset is generated by `scripts/foods/extract_foods_json.py`
 * and must never be edited directly.
 *
 * EN is the canonical fallback. Per-locale overrides arrive via the
 * `*ByLocale` maps as translations land one language at a time.
 */
data class Food(
    val id: String,
    val category: IngredientCategory,
    val nameEn: String,
    val benefitsEn: String,
    val howToConsumeEn: String,
    val whenToConsumeEn: String,
    val deficiencySignsEn: String,
    val excessSignsEn: String,
    val imageFilename: String? = null,
    val nameByLocale: Map<String, String> = emptyMap(),
    val benefitsByLocale: Map<String, String> = emptyMap(),
    val howToConsumeByLocale: Map<String, String> = emptyMap(),
    val whenToConsumeByLocale: Map<String, String> = emptyMap(),
    val deficiencySignsByLocale: Map<String, String> = emptyMap(),
    val excessSignsByLocale: Map<String, String> = emptyMap(),
)

fun Food.displayName(lang: String = currentLanguage()): String =
    nameByLocale[lang] ?: nameEn

fun Food.displayBenefits(lang: String = currentLanguage()): String =
    benefitsByLocale[lang] ?: benefitsEn

fun Food.displayHowToConsume(lang: String = currentLanguage()): String =
    howToConsumeByLocale[lang] ?: howToConsumeEn

fun Food.displayWhenToConsume(lang: String = currentLanguage()): String =
    whenToConsumeByLocale[lang] ?: whenToConsumeEn

fun Food.displayDeficiencySigns(lang: String = currentLanguage()): String =
    deficiencySignsByLocale[lang] ?: deficiencySignsEn

fun Food.displayExcessSigns(lang: String = currentLanguage()): String =
    excessSignsByLocale[lang] ?: excessSignsEn
